# Generated by Django 3.2.6 on 2021-10-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turismo',
            name='contenido',
            field=models.CharField(max_length=900),
        ),
    ]
